import { Build } from "@/components/BuildCard";
import { Deployment } from "@/components/DeploymentCard";

export const mockBuilds: Build[] = [
  {
    id: "1",
    repository: "billing-service",
    branch: "main",
    status: "success",
    duration: 185,
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    commit: "a7f3d8c",
    author: "Sarah Chen",
  },
  {
    id: "2",
    repository: "api-gateway",
    branch: "feature/auth-v2",
    status: "running",
    duration: 120,
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    commit: "b9e2f1a",
    author: "Mike Johnson",
  },
  {
    id: "3",
    repository: "frontend-dashboard",
    branch: "main",
    status: "failed",
    duration: 95,
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    commit: "c4d5e6f",
    author: "Alex Rivera",
  },
  {
    id: "4",
    repository: "notification-service",
    branch: "hotfix/email-queue",
    status: "success",
    duration: 142,
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    commit: "d7e8f9a",
    author: "Emma Wilson",
  },
  {
    id: "5",
    repository: "analytics-engine",
    branch: "develop",
    status: "pending",
    duration: 0,
    timestamp: new Date(Date.now() - 1000 * 30),
    commit: "e1f2g3h",
    author: "James Lee",
  },
];

export const mockDeployments: Deployment[] = [
  {
    id: "1",
    service: "billing-service",
    environment: "production",
    version: "v1.2.9",
    status: "success",
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    deployedBy: "Sarah Chen",
  },
  {
    id: "2",
    service: "api-gateway",
    environment: "staging",
    version: "v2.0.0-rc.1",
    status: "running",
    timestamp: new Date(Date.now() - 1000 * 60 * 3),
    deployedBy: "Mike Johnson",
  },
  {
    id: "3",
    service: "notification-service",
    environment: "production",
    version: "v1.5.3",
    status: "success",
    timestamp: new Date(Date.now() - 1000 * 60 * 35),
    deployedBy: "Emma Wilson",
  },
  {
    id: "4",
    service: "frontend-dashboard",
    environment: "development",
    version: "v3.1.0-beta",
    status: "success",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    deployedBy: "Alex Rivera",
  },
];
